/*
 * Adds the plain-language teaching section used across the course library.
 * Run with: node scripts/enrichLessonExplanations.cjs
 * Safe to rerun: lessons already containing the marker are left alone.
 */
const fs = require('fs');
const path = require('path');

const guides = {
  git: {
    'why-git-and-mental-model': ['Git is like a game with save points. A commit records the whole project at one moment, so a mistake does not erase the route back.', 'When you change a file, it is not saved in Git yet. The staging area is your packing table: choose what belongs in this save point, then commit it.'],
    'installation-and-configuration': ['Installing Git gives your computer the tool. Configuring your name and email puts a return address on every save point you make.', 'Set this up once, then Git can say who made a change. It does not create an online account or upload your work.'],
    'init-status-and-staging': ['`git init` turns an ordinary folder into a project Git can watch. `git status` is a dashboard that tells you what has changed and what is ready to save.', 'Think of staging as putting selected photos into an album before you print it. `git add` selects changes; it does not permanently save them.'],
    'commits-and-history': ['A commit is a labeled save point, not every tiny keystroke. A useful message explains why the change was made, so future-you can understand the history.', 'History is a timeline you can inspect. It is not a backup of only the newest version: each commit gives you a place you can return to.'],
    'undoing-and-recovery': ['Undoing in Git means choosing which stage of a change you want to undo. First ask: is it only edited, staged, committed, or already shared?', 'This is like correcting a draft, an envelope on the desk, or a letter already mailed. The safest tool depends on where the change is.'],
    'branching-and-switching': ['A branch is a separate lane for an idea. You can try a new feature there without blocking the stable main lane.', 'Switching branches changes which version of the project is in your folder. A branch is not a copy you must keep manually; Git remembers where its commits are.'],
    'merging-and-conflict-resolution': ['Merging brings work from one branch into another. Usually Git can combine different changes, like fitting two edits into different paragraphs.', 'A conflict means Git found two competing edits to the same spot and needs a human decision. It is a question, not proof that someone failed.'],
    'stashing-and-tagging': ['A stash is a temporary drawer for unfinished changes when you need a clean desk. A tag is a permanent sticky label on an important commit, such as version 1.0.', 'Do not confuse them: stash is for work you plan to return to; a tag names a point in history that should stay easy to find.'],
    'remotes-and-collaboration': ['A remote is a named copy of the repository somewhere else, often GitHub. `push` sends your commits there; `pull` brings other people’s commits to you.', 'A remote does not magically combine work as you type. You still review incoming changes and resolve conflicts when needed.'],
    'workflows-best-practices-glossary': ['A workflow is the team’s shared routine for making changes safely. It answers small questions early: where work begins, how it is reviewed, and when it reaches main.', 'Good habits are boring on purpose: small commits, clear branch names, and regular updates make problems easier to understand and undo.'],
    'cloning-and-remote-tracking': ['Cloning downloads a full working copy of a project, including its history. Remote-tracking branches are Git’s notes about what the remote looked like last time you checked.', 'They are not live video feeds. Fetching or pulling updates those notes, then you decide how to use the new work.'],
    'pull-requests-and-code-review': ['A pull request is a conversation about a proposed change before it joins the shared branch. It gives teammates a clear place to read, test, and discuss the work.', 'Review is not a judgment of the person. It is a second set of eyes looking for bugs, confusing names, and missing cases.'],
    'rebasing-safely': ['Rebasing moves your branch so it appears to start from a newer commit. It can make a story neat, but it rewrites the labels on commits.', 'Treat shared commits like a group document: do not quietly rewrite them. Rebase your own local work, and communicate before changing shared history.'],
    'finding-and-recovering-work': ['Git keeps more clues than the normal history view shows. Tools such as reflog help you find commits you moved away from or accidentally reset.', 'Recovery works best when you stop making random changes and identify the last known good point. Git often still has the work even when it looks gone.'],
    'release-workflow-capstone': ['A release is a deliberate snapshot people can use, not merely “whatever is on main today.” A repeatable checklist makes releases calmer and easier to trust.', 'The goal is a small, traceable path: make a branch, review it, merge it, tag the version, and record what changed.']
  },
  sql: {
    'intro-to-sql-and-rdbms': ['A database is like a very organized school register. A table holds one kind of thing, each row is one item, and each column is one fact about it.', 'SQL is the question language you use with that register. You ask for information; you do not need to hunt through every row by hand.'],
    'types-of-sql-statements': ['SQL commands fall into jobs: ask for data, add or change data, design tables, and manage access. Knowing the job helps you predict what a command can affect.', '`SELECT` reads. `INSERT`, `UPDATE`, and `DELETE` change stored records. Read first when you are unsure what a changing command will touch.'],
    'select-and-select-distinct': ['`SELECT` is asking a table to show particular columns. `DISTINCT` means “show each repeated answer once,” like making a list of unique club names.', 'It removes duplicate result rows, not duplicate records from the database. Your original table stays untouched.'],
    'filtering-with-where': ['`WHERE` is a filter on a spreadsheet. It keeps rows that match a condition, such as students in grade 10.', 'The filter happens row by row. `WHERE age = 15` checks a value; it does not change anyone’s age.'],
    'logical-operators': ['`AND`, `OR`, and `NOT` let you combine filters, like choosing snacks that are both vegetarian and under a price limit.', '`AND` needs every condition to be true. `OR` needs at least one. Parentheses make your intended grouping clear.'],
    'sorting-and-limiting': ['`ORDER BY` puts results in a useful order, like sorting a leaderboard from highest score to lowest. `LIMIT` then keeps only the number of rows you need.', 'Without `ORDER BY`, “first five” is not a meaningful promise. Always choose an order before asking for top results.'],
    'pattern-matching-and-ranges': ['`LIKE` finds text that fits a pattern, like searching contacts whose name starts with “Sam.” `BETWEEN` checks whether a value falls inside a range.', 'The `%` symbol means any number of characters. It is not the same as `=`: `=` expects an exact match.'],
    'aggregate-functions': ['Aggregate functions turn many rows into one answer. `COUNT` counts, `SUM` adds, `AVG` finds an average, and `MIN` or `MAX` finds an edge.', 'They answer questions such as “How many orders?” rather than showing each order. Missing values can affect some calculations, so check the data.'],
    'group-by-and-having': ['`GROUP BY` makes separate mini-piles before calculating, such as one total for each shop. `HAVING` filters those finished piles.', '`WHERE` filters individual rows before grouping. `HAVING` filters group results after the calculation.'],
    'conditional-logic-case': ['`CASE` lets a query make a choice for each row, like turning scores into “pass” or “needs support.” It creates a label from rules you write.', 'It does not alter the stored score unless you use it in an update. In a `SELECT`, it only changes what the result looks like.'],
    'joining-tables-inner-join': ['A join connects tables using a shared fact, like matching each library loan to the student ID that borrowed it. An inner join keeps only matches found on both sides.', 'The matching columns need related values, not necessarily the same column name. A missing match is left out of an inner join.'],
    'joining-tables-outer-joins': ['Outer joins keep unmatched rows too, which is useful when missing information matters. For example, you can see every student even if some have borrowed no books.', 'A left join keeps every row from the left table. `NULL` in the right-table columns means no matching row was found, not necessarily a mistake.'],
    'create-db-and-tables': ['Designing a table is choosing what facts you need to remember and what kind of value each fact is. It is like designing a form before people fill it in.', 'Give each table one clear job. A table about students should not also store every detail about their borrowed books.'],
    'insert-update-delete': ['`INSERT` adds a new row, `UPDATE` changes rows, and `DELETE` removes rows. These are powerful because they change the saved data.', 'Use a `WHERE` clause when changing or deleting a specific row. Without it, an update or delete can affect the whole table.'],
    'constraints-pk-fk': ['Constraints are guardrails that stop messy data from getting in. A primary key is each row’s unique ID; a foreign key points to a related row in another table.', 'They protect relationships, like stopping a loan from naming a student who does not exist. A key is about identity and links, not about being a secret password.'],
    'modifying-schema-alter-drop': ['The schema is the table’s blueprint. `ALTER` changes the blueprint, while `DROP` removes an object entirely.', 'Changing a blueprint can affect existing data; dropping is much more serious. Check the target and make a backup before destructive changes.']
  },
  ml: {
    'intro-to-machine-learning': ['Machine learning is teaching a computer from examples instead of writing every rule yourself. Like learning to spot a dog after seeing many dogs, it looks for patterns in past examples.', 'A model is the pattern-finder after training. Features are clues you give it; a label is the answer you wanted it to learn.'],
    'applications-of-ml': ['Machine learning fits jobs where examples are plentiful but writing exact rules would be exhausting, such as recommending videos or spotting suspicious card payments.', 'It is not magic or the answer to every app problem. Use ordinary rules when the rule is clear, fair, and dependable.'],
    'types-of-machine-learning': ['Supervised learning learns from examples with answers, like practice questions with a key. Unsupervised learning looks for groups without being told their names.', 'Reinforcement learning improves through rewards and mistakes, like learning a game by scoring points. The right type depends on what feedback you have.'],
    'machine-learning-process': ['A useful ML project is a loop: define the question, collect examples, prepare them, train, test, and improve. The model is only one step in the loop.', 'Start with a clear success measure. “Make a good model” is vague; “catch spam without hiding normal mail” is a testable goal.'],
    'data-collection-and-cleaning': ['A model learns from the examples it sees, so messy or unfair examples teach messy or unfair patterns. Cleaning means checking values, labels, duplicates, and missing pieces.', 'More data is not automatically better. A smaller, relevant, carefully checked set can teach more than a huge pile of confusing examples.'],
    'data-transformation': ['Transformation changes the form of data so patterns are easier for a model to use. Turning a date into day of week is like translating a clue into a more useful language.', 'Do not change data randomly. Each transformation should have a reason and should be applied the same way to training and new data.'],
    'feature-engineering': ['A feature is a clue the model can use. Feature engineering means creating better clues, such as turning start and end time into trip length.', 'A clever feature can help more than a fancier algorithm. But do not sneak in information you would not know when making a real prediction.'],
    'handling-missing-data': ['Missing data is a blank on a form. You can remove the row, fill a sensible value, or add a “was missing” clue, depending on why it is blank.', 'Never treat every blank as zero by habit. Zero is a real answer, while missing means you do not know the answer.'],
    'scaling-and-normalization': ['Scaling puts number columns on comparable measuring sticks. It stops a large-number feature, such as yearly income, from drowning out a small-number feature, such as number of pets.', 'Scaling changes the units, not the underlying order. It is like converting centimetres to metres so measurements are easier to compare.'],
    'linear-regression': ['Linear regression draws the straight trend that best summarizes a relationship, such as how study hours tend to relate to a score. It then uses that trend to estimate a new value.', 'It predicts a number, not a guaranteed future. A good-looking line can still be wrong when the pattern curves, has unusual points, or changes over time.'],
    'logistic-regression': ['Despite its name, logistic regression is often used for a yes-or-no choice, such as “spam or not spam.” It turns clues into a probability between 0 and 1.', 'A probability is not certainty. Choosing a cutoff, like 0.5, is a decision you make after seeing the cost of each kind of mistake.'],
    'decision-trees-and-random-forests': ['A decision tree asks a series of simple questions, like a guessing game: “Is it weekend?” then “Is the price under 10?” A random forest asks many trees and lets them vote.', 'One tree can memorize quirks in its practice data. Many varied trees usually make a steadier decision than one overconfident tree.'],
    'support-vector-machines': ['A support vector machine tries to draw the widest possible gap between groups, like placing a fence with as much space as possible between two teams.', 'The points nearest the fence matter most. When a straight fence will not work, a kernel can help describe a curved boundary.'],
    'ensemble-learning-and-boosting': ['Ensemble learning combines several models, like asking several people before making a difficult call. Boosting builds models one after another, paying extra attention to earlier mistakes.', 'A group is not automatically wise. If every model learns the same bad pattern, their votes can repeat the same error.'],
    'clustering-kmeans-dbscan': ['Clustering groups similar items without labels, like sorting a mixed box of buttons by size and color. K-means looks for a chosen number of centres; DBSCAN looks for dense neighborhoods.', 'Clusters are patterns, not facts stamped on the world. Different settings can create different groupings, so check whether the groups make sense for the real question.'],
    'principal-component-analysis-pca': ['PCA squeezes many related measurements into a few summary directions, like describing a bookshelf with “mostly tall vs. short” and “mostly fiction vs. nonfiction.”', 'It reduces detail to make data easier to view or model. The new directions can be harder to explain, so do not use PCA when every original feature must stay clear.'],
    'anomaly-detection': ['Anomaly detection looks for items that are unusually different from the usual pattern, like noticing one giant expense among many small lunch payments.', 'Unusual does not automatically mean bad. An anomaly is a signal to investigate, not proof of fraud or an error.']
  },
  python: {
    'why-python': ['Python is a way to write precise instructions for a computer. It is popular because the instructions are readable, so you can focus on solving a problem instead of fighting punctuation.', 'Python is not a magic answer machine. It does exactly what you tell it, including mistakes, so clear thinking matters.'],
    'what-is-python': ['Python is like a patient helper that follows written steps. You can use it to sort information, make games, automate boring jobs, and build parts of websites.', 'The interpreter is the program that reads your Python instructions. It follows them from top to bottom unless you tell it to choose or repeat.'],
    'getting-started': ['Running a Python program is like pressing play on a recipe. Write the instructions in a file, then ask Python to read and carry them out.', 'Errors are messages, not grades. Read the first useful line, find the named place in your code, and change one thing at a time.'],
    'hello-world': ['`print()` tells Python to show something on the screen. It is your easiest way to check that a program is doing what you think it is doing.', 'Words need quotation marks because Python must know they are text, not a variable name it should look up.'],
    'variables': ['A variable is a labeled box that holds a value, such as a player name or score. You choose the label so people can understand what the value represents.', 'The label is not the value itself. If you assign a new value to the same variable, the box now holds the new one.'],
    'variables-and-types': ['Variables let you give names to pieces of information so a program can reuse them. A type tells Python what kind of thing is in the box: text, a whole number, or something else.', 'A variable name should describe the value, not the whole story. `score` is easier to understand than `x`.'],
    'variables-and-constants': ['A variable is a labeled box whose value can change while a program runs. A constant is a value you choose to treat as fixed, such as the number of days in a week.', 'Python does not lock constants for you; using an ALL_CAPS name is a promise to other people reading the code that the value should not change.'],
    'data-types': ['Different kinds of information behave differently. You can add numbers, join text, and use true-or-false values to make choices.', 'Do not expect text that looks like a number to act like a number. `"12"` and `12` are different types.'],
    'type-casting': ['Type casting deliberately changes one kind of value into another, like turning the text from a form into a number you can calculate with.', 'Conversion can fail if the text is not shaped like the type you want. Check inputs such as `"twelve"` before treating them as `int`s.'],
    'basic-operators': ['Operators are small symbols that tell Python to do a calculation or comparison. They are the plus, minus, multiply, divide, and “is this equal?” parts of code.', 'Watch the difference between `=` for storing a value and `==` for comparing two values. They look similar but do different jobs.'],
    'operators': ['Operators combine or compare values, like adding prices or checking whether a score passed. They help turn stored data into a useful result.', 'Read calculations in small pieces and use parentheses when the intended order matters. Computers follow rules, not your unstated guess.'],
    'math': ['Python can do everyday maths quickly: totals, averages, remainders, and powers. The remainder operator `%` is especially useful for patterns such as “every second item.”', 'Division can produce a decimal even when numbers divide neatly. Test a few values so you know what type and result you are getting.'],
    'comments': ['Comments are notes for humans reading the code. They explain a reason, a decision, or a tricky part that the code alone does not make clear.', 'Python ignores comments when it runs. A comment cannot fix confusing code; clear names and small steps still matter.'],
    'conditions': ['Conditions let a program choose based on what is true, like deciding whether to bring an umbrella after checking the weather. `if` runs a block only when its question is true.', '`elif` gives another choice and `else` catches the remaining case. Indentation shows which instructions belong to each choice.'],
    'loops': ['A loop repeats a task so you do not copy the same instruction twenty times. It is like checking each item in a shopping basket using the same rule.', 'A `for` loop walks through a collection. A `while` loop repeats while a condition remains true, so it needs a clear way to stop.'],
    'functions': ['A function is a named mini-recipe. You put a useful set of steps in one place, then call it whenever you need that job done.', 'Inputs are what you hand to the recipe; a return value is what it hands back. Printing a result is not the same as returning it for later use.'],
    'scope': ['Scope is where a variable name is known. A variable made inside a function is like a note inside one room: other rooms cannot automatically see it.', 'Keeping values local prevents accidental mix-ups. Pass information into functions and return what you need instead of relying on hidden global boxes.'],
    'input-output': ['Input brings information into a program, and output shows or saves a result. It is a conversation: ask clearly, receive text, then respond usefully.', 'Text entered with `input()` arrives as text. Convert it when you need a number, and handle unexpected answers kindly.'],
    'input-and-output': ['Input brings information into a program, and output shows or saves a result. It is a conversation: ask clearly, receive text, then respond usefully.', 'Text entered with `input()` arrives as text. Convert it when you need a number, and handle unexpected answers kindly.'],
    'string-operations': ['A string is text, such as a name, message, or password. String operations let you join, search, change case, and pull out parts of that text.', 'Strings cannot be changed in place. A method such as `.upper()` gives you a new string, so save it if you need the result.'],
    'strings-deep-dive': ['Text has positions, like letters in a word or seats in a row. Indexing and slicing let you look at one character or a stretch of characters.', 'Python counts from zero, so the first character is position 0. A slice stops before its end position, which is a common off-by-one surprise.'],
    'string-formatting': ['Formatting is a tidy way to place values inside a message, like filling in blanks on a certificate. F-strings keep the text and the changing values easy to read.', 'Put variables inside `{}` in an f-string. Without the `f` before the quote, Python treats those braces as ordinary text.'],
    'indexing': ['Indexing means finding an item by position in an ordered collection. Think of a row of lockers: Python labels the first locker 0, then 1, then 2.', 'Negative indexes count from the end, so `-1` is the last item. Asking for a position that does not exist causes an error.'],
    'lists': ['A list is an ordered, changeable collection, like a shopping list. You can add, remove, replace, and look up items by their position.', 'A list keeps duplicates and order. Changing a list affects the same list object, which matters when more than one variable refers to it.'],
    'lists-and-tuples': ['Lists and tuples both keep items in order. Use a list when the collection may change, and a tuple when the values should stay fixed.', 'The brackets are a clue: lists use `[]`, tuples usually use `()`. Choosing the right one signals your intention to the next reader.'],
    'dicts': ['A dictionary stores named pairs, like a contact card where “name” points to a value and “phone” points to another. You look things up by key, not position.', 'Keys should be unique. Looking up a missing key can fail, so use `.get()` when a value may not be there.'],
    'dictionaries-and-sets': ['Dictionaries connect a unique key to a value; sets keep unique items with no fixed order. Think of a phonebook versus a guest list that avoids duplicates.', 'Use a dictionary when each item needs a detail. Use a set when “is this already here?” is the important question.'],
    'sets': ['A set is a collection that automatically keeps only one copy of each value. It is useful for unique tags, attendees, or items you have already seen.', 'Sets do not promise an order, so do not use index positions with them. Their strength is fast membership checking and duplicate removal.'],
    'composite-types': ['Composite types let one variable hold many related pieces of information. Lists, tuples, dictionaries, and sets each organize those pieces differently.', 'Pick the structure by the question you need to answer: position, fixed order, named lookup, or uniqueness.'],
    'list-comprehensions-and-arrays': ['A list comprehension builds a new list from an old one in one readable line, like making a new list of every price after a discount.', 'It is a compact loop, not a cleverness contest. Use a normal loop when the one-line version would be harder to explain.'],
    'classes-and-objects': ['A class is a blueprint, like a design for a bike. An object is one actual bike made from that blueprint, with its own color and mileage.', 'A class describes what objects can know and do. Each object keeps its own data, even though they share the same blueprint.'],
    'modules-and-packages': ['A module is a Python file you can reuse; a package is a folder that groups related modules. They help large projects stay organized instead of becoming one giant file.', 'Importing lets you use a tool from another module. Choose clear module names so readers can tell where a function comes from.'],
    'exception-handling': ['An exception is Python’s way of saying something unexpected stopped the normal plan, like a missing file or invalid number. Handling it lets your program respond instead of crashing abruptly.', 'Catch the specific problem you expect and explain what to do next. Do not hide every error with a broad `except`, or real bugs become harder to find.'],
    'custom-exceptions': ['A custom exception gives a meaningful name to a problem that matters in your program, such as an impossible age or an empty order. It makes errors easier to understand and handle.', 'Use one when the usual Python error does not explain the situation. The name should describe the problem, not the code line that happened to find it.'],
    'file-handling-basics': ['Files let a program remember information after it stops running. Opening a file is like opening a notebook: choose whether you want to read it, add to it, or replace it.', 'Use `with open(...)` so Python closes the notebook even if something goes wrong. Be careful with write mode because it can replace existing contents.'],
    'libraries-and-ecosystem': ['A project becomes useful when small skills work together. This capstone turns raw inventory records into a report by using collections, functions, and safe handling of odd data.', 'Break the project into tiny jobs: calculate a total, find low stock, then present the answer. If each job is clear, debugging is much less scary.'],
    'quiz': ['A quiz is a chance to retrieve ideas from memory, which is how they become easier to use later. Slow down and trace what the code would do before choosing an answer.', 'When an answer is wrong, name the rule you missed. That turns a guess into a useful note for the next problem.']
  }
};

const root = path.join(process.cwd(), 'src/content/lessons');
for (const pathId of fs.readdirSync(root)) {
  for (const filename of fs.readdirSync(path.join(root, pathId)).filter((file) => file.endsWith('.json'))) {
    const fullPath = path.join(root, pathId, filename);
    const lesson = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    const guide = guides[pathId]?.[lesson.slug];
    if (!guide) throw new Error(`Missing teaching guide for ${pathId}/${lesson.slug}`);
    const [idea, detail] = guide;
    const content = `${idea}\n\n${detail}`;
    const existing = lesson.blocks.find((block) => block.type === 'text' && (block.content.includes('## Make it stick') || block.content.includes('**Explain it back:**')));
    if (existing) {
      existing.content = content;
      fs.writeFileSync(fullPath, `${JSON.stringify(lesson, null, 2)}\n`);
      continue;
    }
    const insertAt = lesson.blocks.findIndex((block) => !['text'].includes(block.type));
    lesson.blocks.splice(insertAt === -1 ? lesson.blocks.length : insertAt, 0, { type: 'text', content });
    lesson.estimatedMinutes = Math.min(12, lesson.estimatedMinutes + 2);
    fs.writeFileSync(fullPath, `${JSON.stringify(lesson, null, 2)}\n`);
  }
}
